title: NoteHub-Mānoa
description: Notes, homework, classses for the UH Community
google_analytics:
show_downloads: false
theme: jekyll-theme-primer
github:
  is_project_page: true
  repository_url: https://github.com/web-warriors-hub/web-warriors-hub.github.io.git
gems:
  - jekyll-mentions
